### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by uskyrt** [mafredri/asustor-radarr#1]
Hello, when I try to install the beta app I get a
'cannot apply settings' warning
![image](https://cloud.githubusercontent.com/assets/10675122/25772756/8655f270-3269-11e7-82bc-b29cca91c828.png)
Any idea how to solve it?
Let me know if you need additional info plz.

Thank you!

**Comment by uskyrt** [comment]
Solved by unticking the upnp setting

**Comment by mafredri** [comment]
@uskyrt thanks for reporting & posting the solution. I can't recall ever seeing a upnp setting, wonder if that's something new they added in ADM?

**Comment by uskyrt** [comment]
I wouldn't say new but has been part of it in the last maybe 6 months?
Screenshot example:
![image](https://cloud.githubusercontent.com/assets/10675122/25773037/56e7afd8-326e-11e7-8601-72ba9129a475.png)

**Comment by mafredri** [comment]
Oh yeah, it's been a while since I installed anything through the web-interface, thanks =).
